### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by takaczapka**
As discussed before.

added a few more koans (in the beginner's section)
changed a sequence of some koans
converted lib/ project to gradle project by merging all sources into one folder (src/main/java, src/main/test) all tests can be run from either IDE or command line (I've spent a while on this one)
introduced a flag in config.properties: enable_expectation_result - the flag when false will make a koans runtime not to show an expected value info. Why? I think if the user knows what is expected, then she might be tempted to copy/paste the result to the source code. So by default I don't wanna show it. If I remember properly Scala/Ruby koans don't show anything like this.
Also, you might see a lot of changes to the fact that I reformatted koans JAVA code to follow JAVA code formatting standards, which among many encourage use of only space white characters (never tabs). Some reference here: https://google.github.io/styleguide/javaguide.html (which actually surprised me with 2-space indentation, not 4-space indentation I'm used to).

### CODE REVIEW

**Comment by matyb** [comment]
sorry taking some time to review, i dig the changes, but there's a ton in this PR!

**Comment by takaczapka** [comment]
Hey, just wanted to say thank you for the project. Kids loved it and were working hard to go through koans. They are building really good foundations of Java thanks to it. Thanks man!

**Comment by matyb** [comment]
Thanks @takaczapka I appreciate the feedback. And the PR as well.

I'll try and actually get it in in next few days, just a **lot** of (so far) good stuff.

**Comment by matyb** [comment]
made it through review, just tackling some "TODOs" before I merge this into master:

1. gradle isn't building component jars, favors uber jar approach (maybe that's better? will take this as is for now probably).
2. .bat and .sh runner are still referencing the component jars, newly built lib.jar (uber jar) doesn't appear to be used?
3. beginner.AboutLoops.basicForLoop1,2,3,4... want to rename to make them descriptive.
4. replace references to ProductionExecutedFromTestDirectories -> ProductionDirectories; remove ProductionExecutedFromTestDirectories (doesn't look necessary after changes)
5. beginner.AboutInheritance has some koans commented out, seems they're repetitive and/or offer little/no value; on fence as to whether I try and demonstrate something with them or remove them...

**Pull request merged**
